### ISSUE TITLE
주차 표기 이슈

### ISSUE THREAD

**Issue by codeup38** [nyeong/nth-week-today#5]
'2023. 2. 5. 오후 3:55:38 기준으로(KMT 15:55, 05/02/2023)
주차 표기 오류가 있는 것으로 보입니다.

ISO 국제 표준에 따르면 한 주의 시작은 월요일이며, 일요일인 현 시각 기준으로는 6주차가 아닌 5주차로 표기되어야 옳습니다.

현재 사이트에서는 6주차로 표기되어 있습니다.
확인하시기 바랍니다. 감사합니다.

Based on the current time of 15:55, 05/02/2023 (KMT) and the international ISO standard, it appears that there is an error in the way the week is being displayed. According to the ISO standard, a week starts on Monday and this current time of Sunday should be represented as the 5th week, not the 6th week. Currently, the site displays it as the 6th week. Please verify and correct this issue. Thank you.

**Comment by nyeong** [comment]
이슈 감사합니다. 확인해보니 자바스크립트의 `getDay()` 함수가 일요일부터 시작하여 생긴 문제였습니다.

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay
